// GENERATED by tool/gen_web_assets.py — mirrors assets/web/*.
// Embedded as constants so the foreground-service isolate (no rootBundle) can serve them.
// If you edit the web assets, regenerate this file.

class WebAssets {
  static const String indexHtml = r'''<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover" />
  <meta name="color-scheme" content="light dark" />
  <title>LocalDrop</title>
  <link rel="stylesheet" href="styles.css" />
</head>
<body>
  <!-- ===== File Manager (always rendered underneath) ===== -->
  <section id="view-app" class="view">
    <header class="appbar">
      <div class="brand">
        <span class="logo small">⬇</span>
        <strong>LocalDrop</strong>
      </div>
      <nav class="tabs" role="tablist">
        <button class="tab active" data-tab="files" role="tab">Files</button>
        <button class="tab" data-tab="upload" role="tab">Upload</button>
      </nav>
      <div class="toolbar-right">
        <button id="view-toggle" class="btn ghost icon-btn" title="Toggle view">☰</button>
        <button id="sort-btn" class="btn ghost icon-btn" title="Sort">⇅</button>
        <div class="conn" id="conn-status" title="Connection status">
          <span class="dot"></span>
        </div>
      </div>
    </header>

    <!-- Sort dropdown -->
    <div id="sort-dropdown" class="dropdown" hidden>
      <div class="dropdown-item" data-sort="name-asc">Name A–Z</div>
      <div class="dropdown-item" data-sort="name-desc">Name Z–A</div>
      <div class="dropdown-item" data-sort="size-asc">Size (smallest first)</div>
      <div class="dropdown-item" data-sort="size-desc">Size (largest first)</div>
      <div class="dropdown-item" data-sort="date-asc">Date (oldest first)</div>
      <div class="dropdown-item" data-sort="date-desc">Date (newest first)</div>
      <div class="dropdown-item" data-sort="type-asc">Type A–Z</div>
      <div class="dropdown-item" data-sort="type-desc">Type Z–A</div>
    </div>

    <div class="tabpanel" id="tab-files">
      <!-- Breadcrumb -->
      <nav id="breadcrumb" class="breadcrumb" aria-label="Folder path"></nav>

      <!-- Search / Filter / Sort row -->
      <div class="topbar">
        <input type="search" id="filter-search" placeholder="Search files…" autocomplete="off" />
        <select id="filter-type">
          <option value="all">All types</option>
          <option value="image">Images</option>
          <option value="video">Videos</option>
          <option value="audio">Audio</option>
          <option value="document">Documents</option>
          <option value="archive">Archives</option>
          <option value="other">Other</option>
        </select>
        <button id="sort-btn-inline" class="btn ghost icon-btn" title="Sort">⇅</button>
        <button id="clear-filters" class="btn ghost" title="Clear filters" hidden>✕</button>
        <span id="filter-count" class="filter-count" hidden></span>
      </div>

      <div class="file-toolbar" id="file-toolbar">
        <label class="checkbox">
          <input type="checkbox" id="select-all" />
          <span>Select all</span>
        </label>
        <button id="download-zip" class="btn primary" disabled>Download selected</button>
        <button id="refresh" class="btn ghost" title="Refresh">⟳</button>
      </div>

      <div id="file-list" class="file-list" aria-live="polite"></div>
      <p id="files-empty" class="muted empty" hidden>No files in this folder.</p>
    </div>

    <!-- Upload tab -->
    <div class="tabpanel" id="tab-upload" hidden>
      <div id="dropzone" class="dropzone">
        <div class="dz-inner">
          <div class="dz-icon">⤴</div>
          <p><strong>Drop files here</strong> or</p>
          <button id="pick-files" class="btn primary" type="button">Choose files</button>
          <input id="file-input" type="file" multiple hidden />
        </div>
      </div>
      <div id="upload-list" class="upload-list"></div>
    </div>

    <div id="toast" class="toast" hidden></div>
  </section>

  <!-- ===== PIN Modal (overlay) ===== -->
  <div id="pin-overlay" class="pin-overlay">
    <div class="pin-card">
      <div class="logo">⬇</div>
      <h1>LocalDrop</h1>
      <p class="muted">Enter the 6-digit PIN shown on the phone.</p>
      <form id="pin-form" autocomplete="off">
        <input
          id="pin-input"
          class="pin-input"
          inputmode="numeric"
          pattern="[0-9]*"
          maxlength="6"
          placeholder="••••••"
          aria-label="PIN"
          autofocus
        />
      </form>
      <p id="pin-error" class="error" hidden>Wrong PIN. Try again.</p>
    </div>
  </div>

  <script src="app.js" defer></script>
</body>
</html>
''';
  static const String indexHtmlType = "text/html; charset=utf-8";

  static const String stylesCss = r''':root {
  --bg: #f6f7f9;
  --surface: #ffffff;
  --surface-2: #eef0f3;
  --surface-3: #e2e5ea;
  --text: #14181f;
  --text-secondary: #6b7480;
  --border: #e2e5ea;
  --primary: #2563eb;
  --primary-ink: #ffffff;
  --danger: #e11d48;
  --ok: #16a34a;
  --radius: 14px;
  --shadow: 0 1px 2px rgba(16, 24, 40, 0.06), 0 8px 24px rgba(16, 24, 40, 0.06);
}

@media (prefers-color-scheme: dark) {
  :root {
    --bg: #0d1117;
    --surface: #161b22;
    --surface-2: #1f2630;
    --surface-3: #2a313c;
    --text: #e6edf3;
    --text-secondary: #8b949e;
    --border: #2a313c;
    --primary: #4d8bff;
    --primary-ink: #0d1117;
    --danger: #ff5c7c;
    --ok: #3fb950;
    --shadow: 0 1px 2px rgba(0, 0, 0, 0.4), 0 10px 30px rgba(0, 0, 0, 0.35);
  }
}

* { box-sizing: border-box; }

html, body {
  margin: 0;
  padding: 0;
  height: 100%;
}

body {
  font-family: system-ui, -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  background: var(--bg);
  color: var(--text);
  -webkit-font-smoothing: antialiased;
}

.muted { color: var(--text-secondary); }
.error { color: var(--danger); font-size: 0.9rem; margin-top: 0.75rem; }
.empty { text-align: center; padding: 2rem 0; }

.view {
  min-height: 100%;
  display: flex;
  flex-direction: column;
}

/* ---------- App shell ---------- */
#view-app { justify-content: flex-start; padding: 0; }
.appbar {
  width: 100%;
  display: flex;
  align-items: center;
  gap: 1rem;
  padding: 0.85rem 1.25rem;
  background: var(--surface);
  border-bottom: 1px solid var(--border);
  position: sticky;
  top: 0;
  z-index: 5;
}
.brand { display: flex; align-items: center; gap: 0.5rem; font-size: 1.05rem; }
.toolbar-right { display: flex; align-items: center; gap: 0.5rem; margin-left: auto; }
.icon-btn {
  width: 36px;
  height: 36px;
  padding: 0;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  border-radius: 10px;
  font-size: 1.1rem;
}
.conn .dot {
  display: inline-block;
  width: 10px; height: 10px;
  border-radius: 50%;
  background: var(--text-secondary);
  transition: background 0.2s ease;
}
.conn.ok .dot { background: var(--ok); box-shadow: 0 0 0 4px rgba(63,185,80,0.18); }
.conn.bad .dot { background: var(--danger); box-shadow: 0 0 0 4px rgba(225,29,72,0.18); }

.tabpanel { width: 100%; max-width: 880px; margin: 0 auto; padding: 1rem 1.25rem; }

/* ---------- Breadcrumb ---------- */
.breadcrumb {
  display: flex;
  align-items: center;
  gap: 0.35rem;
  padding: 0.5rem 0;
  font-size: 0.9rem;
  color: var(--text-secondary);
  flex-wrap: wrap;
}
.breadcrumb-sep { color: var(--text-secondary); opacity: 0.6; }
.breadcrumb-item {
  background: none;
  border: none;
  color: var(--primary);
  cursor: pointer;
  padding: 0.2rem 0.4rem;
  border-radius: 6px;
  font-size: 0.9rem;
  transition: background 0.1s ease;
}
.breadcrumb-item:hover { background: var(--surface-2); }
.breadcrumb-item.current { color: var(--text); font-weight: 600; cursor: default; }
.breadcrumb-item.current:hover { background: none; }

/* ---------- Topbar ---------- */
.topbar {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  margin-bottom: 0.75rem;
  flex-wrap: wrap;
}
.topbar input[type="search"] {
  flex: 1 1 180px;
  padding: 0.55rem 0.85rem;
  border-radius: 10px;
  border: 1px solid var(--border);
  background: var(--surface-2);
  color: var(--text);
  font-size: 0.95rem;
  outline: none;
  transition: border-color 0.15s ease;
}
.topbar input[type="search"]:focus { border-color: var(--primary); }
.topbar select {
  padding: 0.55rem 0.6rem;
  border-radius: 10px;
  border: 1px solid var(--border);
  background: var(--surface-2);
  color: var(--text);
  font-size: 0.9rem;
  outline: none;
}
.filter-count {
  font-size: 0.8rem;
  color: var(--primary);
  font-weight: 600;
  margin-left: 0.25rem;
}

/* ---------- Sort dropdown ---------- */
.dropdown {
  position: absolute;
  top: 56px;
  right: 1rem;
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 12px;
  box-shadow: var(--shadow);
  z-index: 20;
  min-width: 220px;
  padding: 0.5rem 0;
}
.dropdown-item {
  padding: 0.6rem 1rem;
  cursor: pointer;
  font-size: 0.95rem;
  transition: background 0.1s ease;
}
.dropdown-item:hover { background: var(--surface-2); }

/* ---------- Filter bar ---------- */
.filter-bar {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  margin-bottom: 0.75rem;
  flex-wrap: wrap;
}
.filter-bar input[type="search"] {
  flex: 1 1 180px;
  padding: 0.55rem 0.85rem;
  border-radius: 10px;
  border: 1px solid var(--border);
  background: var(--surface-2);
  color: var(--text);
  font-size: 0.95rem;
  outline: none;
  transition: border-color 0.15s ease;
}
.filter-bar input[type="search"]:focus { border-color: var(--primary); }
.filter-bar select {
  padding: 0.55rem 0.6rem;
  border-radius: 10px;
  border: 1px solid var(--border);
  background: var(--surface-2);
  color: var(--text);
  font-size: 0.9rem;
  outline: none;
}
.filter-count {
  font-size: 0.8rem;
  color: var(--primary);
  font-weight: 600;
  margin-left: 0.25rem;
}

/* ---------- File toolbar ---------- */
.file-toolbar {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  margin-bottom: 0.75rem;
  flex-wrap: wrap;
}
.file-toolbar.hidden { display: none; }

/* ---------- File list ---------- */
.file-list { display: flex; flex-direction: column; gap: 0.35rem; }
.file-row {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  padding: 0.65rem 0.85rem;
  border-radius: 12px;
  background: var(--surface);
  border: 1px solid transparent;
  transition: background 0.1s ease, border-color 0.15s ease;
  cursor: pointer;
  user-select: none;
  position: relative;
}
.file-row:hover { background: var(--surface-2); }
.file-row.selected {
  background: color-mix(in srgb, var(--primary) 10%, var(--surface));
  border-color: var(--primary);
}
.file-check {
  width: 18px;
  height: 18px;
  accent-color: var(--primary);
  cursor: pointer;
  flex: none;
  visibility: hidden;
}
.file-row:hover .file-check,
.file-row.selected .file-check,
.file-toolbar.force-show .file-check {
  visibility: visible;
}
.file-icon { font-size: 1.4rem; width: 2rem; text-align: center; flex: none; }
.file-meta { flex: 1; min-width: 0; }
.file-name {
  font-weight: 500;
  font-size: 0.95rem;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.file-sub {
  font-size: 0.78rem;
  color: var(--text-secondary);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.file-actions { display: flex; align-items: center; gap: 0.5rem; flex: none; }
.file-row .btn.ghost { opacity: 0; transition: opacity 0.1s ease; }
.file-row:hover .btn.ghost,
.file-row.selected .btn.ghost { opacity: 1; }

/* ---------- Download progress ---------- */
.file-progress {
  position: absolute;
  left: 0; right: 0; bottom: 0;
  height: 4px;
  background: var(--surface-2);
  border-radius: 0 0 12px 12px;
  overflow: hidden;
}
.file-progress > span {
  display: block;
  height: 100%;
  width: 0;
  background: var(--primary);
  transition: width 0.2s ease;
}
.file-row.downloading .file-progress { display: block; }
.file-row .file-progress { display: none; }

/* ---------- Grid view ---------- */
.file-list.grid-view {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(140px, 1fr));
  gap: 0.75rem;
}
.file-list.grid-view .file-row {
  flex-direction: column;
  align-items: center;
  text-align: center;
  padding: 1rem 0.5rem;
  gap: 0.5rem;
}
.file-list.grid-view .file-icon { font-size: 2.2rem; width: auto; }
.file-list.grid-view .file-meta { width: 100%; }
.file-list.grid-view .file-sub { font-size: 0.7rem; }
.file-list.grid-view .file-actions { display: none; }
.file-list.grid-view .file-check { visibility: visible; }

/* ---------- Dropzone ---------- */
.dropzone {
  border: 2px dashed var(--border);
  border-radius: var(--radius);
  padding: 2.5rem 1rem;
  text-align: center;
  transition: border-color 0.15s ease, background 0.15s ease;
}
.dropzone.over { border-color: var(--primary); background: color-mix(in srgb, var(--primary) 10%, var(--surface)); }
.dz-icon { font-size: 2.5rem; }
.dz-inner p { color: var(--text-secondary); margin: 0.5rem 0 0.9rem; }

.upload-list { margin-top: 1.25rem; display: flex; flex-direction: column; gap: 0.6rem; }
.up-row {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  padding: 0.7rem 0.9rem;
  box-shadow: var(--shadow);
}
.up-head { display: flex; justify-content: space-between; gap: 1rem; margin-bottom: 0.5rem; }
.up-name { font-weight: 600; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.up-sub { font-size: 0.8rem; color: var(--text-secondary); }
.progress {
  height: 8px;
  background: var(--surface-2);
  border-radius: 999px;
  overflow: hidden;
}
.progress > span {
  display: block;
  height: 100%;
  width: 0;
  background: var(--primary);
  border-radius: 999px;
  transition: width 0.2s ease;
}

/* ---------- PIN Modal ---------- */
.pin-overlay {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.5);
  backdrop-filter: blur(8px);
  -webkit-backdrop-filter: blur(8px);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 100;
  opacity: 1;
  transition: opacity 0.25s ease;
}
.pin-overlay.fade-out {
  opacity: 0;
  pointer-events: none;
}
.pin-card {
  width: 100%;
  max-width: 380px;
  text-align: center;
  padding: 2.5rem 2rem;
  background: var(--surface);
  border-radius: 20px;
  box-shadow: var(--shadow);
}
.logo {
  font-size: 2.5rem;
  line-height: 1;
}
.logo.small { font-size: 1.1rem; }
.pin-card h1 { margin: 0.5rem 0 0.25rem; font-size: 1.6rem; }
.pin-input {
  margin-top: 1.25rem;
  width: 100%;
  font-size: 2rem;
  letter-spacing: 0.5rem;
  text-align: center;
  padding: 0.75rem;
  border-radius: var(--radius);
  border: 1px solid var(--border);
  background: var(--surface-2);
  color: var(--text);
  outline: none;
  transition: border-color 0.15s ease;
}
.pin-input:focus { border-color: var(--primary); }

/* ---------- Toast ---------- */
.toast {
  position: fixed;
  left: 50%;
  bottom: 1.5rem;
  transform: translateX(-50%);
  background: var(--text);
  color: var(--bg);
  padding: 0.7rem 1.1rem;
  border-radius: 10px;
  font-size: 0.9rem;
  box-shadow: var(--shadow);
  z-index: 20;
  animation: toast-in 0.2s ease;
}
@keyframes toast-in {
  from { opacity: 0; transform: translate(-50%, 8px); }
  to { opacity: 1; transform: translate(-50%, 0); }
}

/* ---------- Misc ---------- */
.btn {
  border: 1px solid var(--border);
  background: var(--surface);
  color: var(--text);
  padding: 0.5rem 0.9rem;
  border-radius: 10px;
  font-size: 0.9rem;
  cursor: pointer;
  transition: transform 0.08s ease, background 0.15s ease, opacity 0.15s ease;
}
.btn:active { transform: scale(0.98); }
.btn.primary { background: var(--primary); color: var(--primary-ink); border-color: transparent; }
.btn.ghost { background: transparent; border-color: transparent; }
.btn:disabled { opacity: 0.45; cursor: not-allowed; }
.checkbox { display: inline-flex; align-items: center; gap: 0.4rem; color: var(--text-secondary); cursor: pointer; font-size: 0.9rem; }

@media (max-width: 520px) {
  .file-sub { font-size: 0.7rem; }
  .tabpanel { padding: 0.85rem; }
  .pin-card { padding: 2rem 1.25rem; }
}
''';
  static const String stylesCssType = "text/css; charset=utf-8";

  static const String appJs = r'''/* LocalDrop browser client — vanilla JS, no frameworks. */
(function () {
  "use strict";

  const els = {
    body: document.body,
    pinOverlay: document.getElementById("pin-overlay"),
    pinForm: document.getElementById("pin-form"),
    pinInput: document.getElementById("pin-input"),
    pinError: document.getElementById("pin-error"),
    viewApp: document.getElementById("view-app"),
    fileList: document.getElementById("file-list"),
    filesEmpty: document.getElementById("files-empty"),
    breadcrumb: document.getElementById("breadcrumb"),
    selectAll: document.getElementById("select-all"),
    downloadZip: document.getElementById("download-zip"),
    refresh: document.getElementById("refresh"),
    dropzone: document.getElementById("dropzone"),
    pickFiles: document.getElementById("pick-files"),
    fileInput: document.getElementById("file-input"),
    uploadList: document.getElementById("upload-list"),
    conn: document.getElementById("conn-status"),
    toast: document.getElementById("toast"),
    filterSearch: document.getElementById("filter-search"),
    filterType: document.getElementById("filter-type"),
    clearFilters: document.getElementById("clear-filters"),
    filterCount: document.getElementById("filter-count"),
    viewToggle: document.getElementById("view-toggle"),
    sortBtn: document.getElementById("sort-btn"),
    sortBtnInline: document.getElementById("sort-btn-inline"),
    sortDropdown: document.getElementById("sort-dropdown"),
    fileToolbar: document.getElementById("file-toolbar"),
  };

  const state = {
    token: null,
    files: [],
    filteredFiles: [],
    selected: new Set(),
    uploads: new Map(),
    filters: { search: "", type: "all" },
    viewMode: "list",
    sortKey: "name",
    sortDir: "asc",
    currentPath: "",
  };

  /* ---------- logging ---------- */
  function log(area, message) {
    const ts = new Date().toISOString().split('T')[1].slice(0, -1);
    const entry = `[${ts}] [${area}] ${message}`;
    console.log(entry);
  }

  /* ---------- helpers ---------- */
  function authHeaders() {
    const h = { "X-Requested-With": "fetch" };
    if (state.token) h["Authorization"] = "Bearer " + state.token;
    return h;
  }

  async function api(path, options) {
    options = options || {};
    options.credentials = "same-origin";
    options.headers = Object.assign(authHeaders(), options.headers || {});
    log('http', `request ${path}`);
    const res = await fetch(path, options);
    log('http', `response ${path} status=${res.status}`);
    if (res.status === 401) {
      logout();
      throw new Error("unauthorized");
    }
    if (!res.ok) throw new Error("http_" + res.status);
    return res;
  }

  function showToast(msg, ms) {
    els.toast.textContent = msg;
    els.toast.hidden = false;
    clearTimeout(showToast._t);
    showToast._t = setTimeout(() => (els.toast.hidden = true), ms || 2600);
  }

  function setConn(ok) {
    els.conn.classList.toggle("ok", ok === true);
    els.conn.classList.toggle("bad", ok === false);
  }

  function fmtSize(bytes) {
    if (bytes == null) return "";
    const u = ["B", "KB", "MB", "GB", "TB"];
    let i = 0;
    let n = bytes;
    while (n >= 1024 && i < u.length - 1) { n /= 1024; i++; }
    return (i === 0 ? n : n.toFixed(n < 10 ? 2 : 1)) + " " + u[i];
  }

  function fmtDate(ts) {
    if (!ts) return "";
    const d = new Date(ts * 1000);
    return d.toLocaleDateString() + " " + d.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
  }

  function iconFor(name, isDirectory) {
    if (isDirectory) return "📁";
    const ext = (name.split(".").pop() || "").toLowerCase();
    const map = {
      png: "🖼", jpg: "🖼", jpeg: "🖼", gif: "🖼", webp: "🖼", svg: "🖼", heic: "🖼",
      mp4: "🎞", mov: "🎞", mkv: "🎞", webm: "🎞", avi: "🎞",
      mp3: "🎵", wav: "🎵", ogg: "🎵", flac: "🎵", m4a: "🎵",
      pdf: "📄", doc: "📝", docx: "📝", txt: "📝", md: "📝", rtf: "📝",
      xls: "📊", xlsx: "📊", csv: "📊",
      zip: "🗜", rar: "🗜", "7z": "🗜", gz: "🗜", tar: "🗜",
      apk: "📦", exe: "⚙",
    };
    if (map[ext]) return map[ext];
    return "📄";
  }

  function escapeHtml(s) {
    return String(s).replace(/[&<>"']/g, (c) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c])
    );
  }

  function uuid() {
    return (crypto.randomUUID && crypto.randomUUID()) ||
      (Date.now().toString(36) + Math.random().toString(36).slice(2));
  }

  /* ---------- filters ---------- */
  const TYPE_MAP = {
    image: ["png","jpg","jpeg","gif","webp","svg","heic","bmp","ico"],
    video: ["mp4","mov","mkv","webm","avi","flv","wmv"],
    audio: ["mp3","wav","ogg","flac","m4a","aac","wma"],
    document: ["pdf","doc","docx","txt","md","rtf","odt","ppt","pptx","xls","xlsx","csv"],
    archive: ["zip","rar","7z","gz","tar","bz2"],
  };

  function matchType(name, type) {
    if (type === "all") return true;
    const ext = (name.split(".").pop() || "").toLowerCase();
    return (TYPE_MAP[type] || []).includes(ext) || (type === "other" && !Object.values(TYPE_MAP).some(arr => arr.includes(ext)));
  }

  function matchSize(size, range) {
    if (range === "all" || size == null) return range === "all";
    const mb = size / (1024 * 1024);
    switch (range) {
      case "small": return mb < 1;
      case "medium": return mb >= 1 && mb <= 100;
      case "large": return mb > 100;
      default: return true;
    }
  }

  function matchDate(ts, range) {
    if (range === "all" || !ts) return range === "all";
    const now = Date.now() / 1000;
    const diff = now - ts;
    switch (range) {
      case "today": return diff < 86400;
      case "week": return diff < 7 * 86400;
      case "month": return diff < 30 * 86400;
      case "older": return diff >= 30 * 86400;
      default: return true;
    }
  }

  function sortFiles(files) {
    const key = state.sortKey;
    const dir = state.sortDir === "asc" ? 1 : -1;
    return files.slice().sort((a, b) => {
      if (a.isDirectory !== b.isDirectory) return a.isDirectory ? -1 : 1;
      let va, vb;
      if (key === "name") { va = a.name.toLowerCase(); vb = b.name.toLowerCase(); }
      else if (key === "size") { va = a.size || 0; vb = b.size || 0; }
      else if (key === "date") { va = a.modified || 0; vb = b.modified || 0; }
      else if (key === "type") { va = (a.name.split(".").pop() || "").toLowerCase(); vb = (b.name.split(".").pop() || "").toLowerCase(); }
      else { va = a.name.toLowerCase(); vb = b.name.toLowerCase(); }
      if (va < vb) return -1 * dir;
      if (va > vb) return 1 * dir;
      return 0;
    });
  }

  function applyFilters() {
    const f = state.filters;
    state.filteredFiles = state.files.filter((file) => {
      if (f.search && !file.name.toLowerCase().includes(f.search.toLowerCase())) return false;
      if (!matchType(file.name, f.type)) return false;
      return true;
    });
    state.filteredFiles = sortFiles(state.filteredFiles);
    renderFiles();
    updateFilterUI();
    saveFilters();
  }

  function updateFilterUI() {
    const f = state.filters;
    const active = (f.search ? 1 : 0) + (f.type !== "all" ? 1 : 0);
    els.clearFilters.hidden = active === 0;
    els.filterCount.hidden = active === 0;
    els.filterCount.textContent = active + " filter" + (active === 1 ? "" : "s") + " active";
  }

  function loadFilters() {
    try {
      const saved = localStorage.getItem("localdrop_filters");
      if (saved) {
        const parsed = JSON.parse(saved);
        state.filters.search = parsed.search || "";
        state.filters.type = parsed.type || "all";
      }
    } catch (_) {}
    els.filterSearch.value = state.filters.search;
    els.filterType.value = state.filters.type;
  }

  function saveFilters() {
    try {
      localStorage.setItem("localdrop_filters", JSON.stringify(state.filters));
    } catch (_) {}
  }

  function clearAllFilters() {
    state.filters = { search: "", type: "all" };
    els.filterSearch.value = "";
    els.filterType.value = "all";
    applyFilters();
  }

  /* ---------- breadcrumbs ---------- */
  function renderBreadcrumb() {
    els.breadcrumb.innerHTML = "";
    const parts = state.currentPath ? state.currentPath.split("/").filter(Boolean) : [];
    const allParts = ["Home", ...parts];

    allParts.forEach((part, index) => {
      if (index > 0) {
        const sep = document.createElement("span");
        sep.className = "breadcrumb-sep";
        sep.textContent = "/";
        els.breadcrumb.appendChild(sep);
      }
      const btn = document.createElement("button");
      btn.className = "breadcrumb-item";
      if (index === allParts.length - 1) btn.classList.add("current");
      btn.textContent = part;
      if (index < allParts.length - 1) {
        btn.addEventListener("click", () => {
          const targetPath = parts.slice(0, index).join("/");
          state.currentPath = targetPath;
          loadFiles();
        });
      }
      els.breadcrumb.appendChild(btn);
    });
  }

  /* ---------- auth / PIN modal ---------- */
  function showPinModal() {
    els.pinOverlay.classList.remove("fade-out");
    els.pinOverlay.hidden = false;
    els.pinInput.value = "";
    els.pinError.hidden = true;
    setTimeout(() => els.pinInput.focus(), 100);
  }

  function hidePinModal() {
    els.pinOverlay.classList.add("fade-out");
    setTimeout(() => { els.pinOverlay.hidden = true; }, 250);
  }

  els.pinForm.addEventListener("submit", async (e) => {
    e.preventDefault();
    const pin = els.pinInput.value.trim();
    if (pin.length !== 6) return;
    log('auth', 'attempt');
    try {
      const res = await fetch("/api/auth", {
        method: "POST",
        credentials: "same-origin",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ pin }),
      });
      if (!res.ok) {
        log('auth', 'failure');
        els.pinError.hidden = false;
        els.pinInput.value = "";
        return;
      }
      const data = await res.json();
      state.token = data.token;
      log('auth', 'success');
      hidePinModal();
      loadFiles();
    } catch (err) {
      log('auth', 'error: ' + err.message);
      els.pinError.hidden = false;
      els.pinError.textContent = "Connection failed. Is the phone still on the network?";
    }
  });

  els.pinInput.addEventListener("input", () => {
    els.pinInput.value = els.pinInput.value.replace(/\D/g, "").slice(0, 6);
    els.pinError.hidden = true;
    if (els.pinInput.value.length === 6) els.pinForm.requestSubmit();
  });

  function logout() {
    state.token = null;
    state.selected.clear();
    state.currentPath = "";
    showPinModal();
  }

  /* ---------- files ---------- */
  async function loadFiles() {
    if (!state.token) return;
    try {
      const pathParam = state.currentPath ? `?path=${encodeURIComponent(state.currentPath)}` : "";
      const res = await api("/api/files" + pathParam);
      const data = await res.json();
      state.files = data.files || [];
      applyFilters();
      renderBreadcrumb();
      setConn(true);
    } catch (err) {
      if (err.message !== "unauthorized") {
        setConn(false);
        showToast("Could not reach the phone.");
      }
    }
  }

  function renderFiles() {
    const list = state.filteredFiles;
    els.fileList.innerHTML = "";
    els.filesEmpty.hidden = list.length > 0;
    els.fileList.classList.toggle("grid-view", state.viewMode === "grid");

    for (const f of list) {
      const row = document.createElement("div");
      row.className = "file-row";
      if (state.selected.has(f.name)) row.classList.add("selected");
      row.dataset.name = f.name;

      const checked = state.selected.has(f.name);
      row.innerHTML = `
        <input type="checkbox" class="file-check" ${checked ? "checked" : ""} />
        <div class="file-icon">${iconFor(f.name, f.isDirectory)}</div>
        <div class="file-meta">
          <div class="file-name">${escapeHtml(f.name)}</div>
          <div class="file-sub">${f.isDirectory ? 'Folder' : fmtSize(f.size) + ' · ' + fmtDate(f.modified)}</div>
        </div>
        <div class="file-actions">
          ${f.isDirectory ? '' : '<button class="btn ghost dl" title="Download">↓</button>'}
        </div>
        <div class="file-progress"><span></span></div>`;

      const checkbox = row.querySelector(".file-check");
      checkbox.addEventListener("change", (e) => {
        e.stopPropagation();
        if (e.target.checked) state.selected.add(f.name);
        else state.selected.delete(f.name);
        row.classList.toggle("selected", e.target.checked);
        updateSelectionUI();
      });

      row.addEventListener("click", (e) => {
        if (e.target === checkbox) return;
        if (f.isDirectory) {
          const newPath = state.currentPath ? state.currentPath + "/" + f.name : f.name;
          state.currentPath = newPath;
          loadFiles();
          return;
        }
        if (state.isSelecting || e.shiftKey || e.ctrlKey || e.metaKey) {
          if (state.selected.has(f.name)) state.selected.delete(f.name);
          else state.selected.add(f.name);
          renderFiles();
        } else {
          downloadFile(f.name, row);
        }
      });

      row.addEventListener("contextmenu", (e) => {
        e.preventDefault();
        if (state.selected.has(f.name)) state.selected.delete(f.name);
        else state.selected.add(f.name);
        renderFiles();
      });

      if (!f.isDirectory) {
        row.querySelector(".dl").addEventListener("click", (e) => {
          e.stopPropagation();
          downloadFile(f.name, row);
        });
      }

      els.fileList.appendChild(row);
    }
    updateSelectionUI();
  }

  function updateSelectionUI() {
    els.downloadZip.disabled = state.selected.size === 0;
    els.selectAll.checked = state.filteredFiles.length > 0 && state.selected.size === state.filteredFiles.length;
    els.fileToolbar.classList.toggle("force-show", state.selected.size > 0);
  }

  els.selectAll.addEventListener("change", (e) => {
    if (e.target.checked) state.filteredFiles.forEach((f) => state.selected.add(f.name));
    else state.selected.clear();
    renderFiles();
  });

  els.refresh.addEventListener("click", loadFiles);

  els.filterSearch.addEventListener("input", () => {
    state.filters.search = els.filterSearch.value;
    applyFilters();
  });

  els.filterType.addEventListener("change", () => {
    state.filters.type = els.filterType.value;
    applyFilters();
  });

  els.clearFilters.addEventListener("click", clearAllFilters);

  els.viewToggle.addEventListener("click", () => {
    state.viewMode = state.viewMode === "list" ? "grid" : "list";
    renderFiles();
  });

  function openSortDropdown() {
    els.sortDropdown.hidden = !els.sortDropdown.hidden;
  }
  els.sortBtn.addEventListener("click", (e) => {
    e.stopPropagation();
    openSortDropdown();
  });
  els.sortBtnInline.addEventListener("click", (e) => {
    e.stopPropagation();
    openSortDropdown();
  });

  document.addEventListener("click", () => {
    els.sortDropdown.hidden = true;
  });

  els.sortDropdown.addEventListener("click", (e) => {
    const item = e.target.closest(".dropdown-item");
    if (!item) return;
    const val = item.dataset.sort;
    const [key, dir] = val.split("-");
    state.sortKey = key;
    state.sortDir = dir;
    applyFilters();
    els.sortDropdown.hidden = true;
  });

  els.downloadZip.addEventListener("click", async () => {
    const names = Array.from(state.selected);
    if (!names.length) return;
    try {
      const q = encodeURIComponent(names.join(","));
      const res = await api("/api/download-zip?files=" + q);
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = "localdrop.zip";
      document.body.appendChild(a);
      a.click();
      a.remove();
      setTimeout(() => URL.revokeObjectURL(url), 5000);
    } catch (err) {
      showToast("Download failed.");
    }
  });

  async function downloadFile(name, row) {
    log('download', 'start name=' + name);
    const progressBar = row ? row.querySelector('.file-progress > span') : null;
    const xhr = new XMLHttpRequest();
    xhr.open("GET", "/api/download/" + encodeURIComponent(name), true);
    xhr.setRequestHeader("X-Requested-With", "fetch");
    if (state.token) xhr.setRequestHeader("Authorization", "Bearer " + state.token);
    xhr.responseType = "blob";

    xhr.onprogress = (e) => {
      if (e.lengthComputable && progressBar) {
        const p = (e.loaded / e.total) * 100;
        progressBar.style.width = p.toFixed(1) + "%";
      }
    };

    xhr.onload = () => {
      if (xhr.status >= 200 && xhr.status < 300) {
        const blob = xhr.response;
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = name;
        document.body.appendChild(a);
        a.click();
        a.remove();
        setTimeout(() => URL.revokeObjectURL(url), 5000);
        if (progressBar) {
          progressBar.style.width = "100%";
          setTimeout(() => { progressBar.style.width = "0"; }, 1200);
        }
        log('download', 'complete name=' + name);
      } else {
        log('download', 'failed name=' + name + ' status=' + xhr.status);
        showToast("Download failed.");
        if (progressBar) progressBar.style.width = "0";
      }
      if (row) row.classList.remove("downloading");
    };

    xhr.onerror = () => {
      log('download', 'error name=' + name);
      showToast("Download error.");
      if (progressBar) progressBar.style.width = "0";
      if (row) row.classList.remove("downloading");
    };

    if (row) row.classList.add("downloading");
    xhr.send();
  }

  /* ---------- tabs ---------- */
  const tabs = Array.from(document.querySelectorAll(".tab"));
  const tabFiles = document.getElementById("tab-files");
  const tabUpload = document.getElementById("tab-upload");

  tabs.forEach((tab) => {
    tab.addEventListener("click", () => {
      tabs.forEach((t) => t.classList.remove("active"));
      tab.classList.add("active");
      const name = tab.dataset.tab;
      tabFiles.hidden = name !== "files";
      tabUpload.hidden = name !== "upload";
    });
  });

  /* ---------- upload (XHR gives reliable progress) ---------- */
  els.pickFiles.addEventListener("click", () => els.fileInput.click());
  els.fileInput.addEventListener("change", (e) => {
    handleFiles(e.target.files);
    els.fileInput.value = "";
  });

  ["dragenter", "dragover"].forEach((ev) =>
    els.dropzone.addEventListener(ev, (e) => {
      e.preventDefault();
      els.dropzone.classList.add("over");
    })
  );
  ["dragleave", "drop"].forEach((ev) =>
    els.dropzone.addEventListener(ev, (e) => {
      e.preventDefault();
      els.dropzone.classList.remove("over");
    })
  );
  els.dropzone.addEventListener("drop", (e) => {
    if (e.dataTransfer && e.dataTransfer.files) handleFiles(e.dataTransfer.files);
  });

  function handleFiles(fileList) {
    for (const file of Array.from(fileList)) startUpload(file);
  }

  function startUpload(file) {
    const id = uuid();
    const fd = new FormData();
    fd.append("file", file, file.name);
    log('upload', 'start name=' + file.name + ' size=' + file.size);

    const row = document.createElement("div");
    row.className = "up-row";
    row.innerHTML = `
      <div class="up-head">
        <span class="up-name">${escapeHtml(file.name)}</span>
        <span class="up-sub pct-head">0%</span>
      </div>
      <div class="progress"><span></span></div>
      <div class="up-sub pct-foot">0 / ${fmtSize(file.size)} · preparing…</div>`;
    els.uploadList.prepend(row);
    const bar = row.querySelector(".progress > span");
    const pct = row.querySelector(".pct-foot");
    const subHead = row.querySelector(".pct-head");

    const xhr = new XMLHttpRequest();
    xhr.open("POST", "/api/upload?id=" + id);
    xhr.setRequestHeader("X-Requested-With", "fetch");
    if (state.token) xhr.setRequestHeader("Authorization", "Bearer " + state.token);
    xhr.withCredentials = true;
    xhr.timeout = 0;

    xhr.upload.onprogress = (e) => {
      if (e.lengthComputable) {
        const p = (e.loaded / e.total) * 100;
        bar.style.width = p.toFixed(1) + "%";
        subHead.textContent = p.toFixed(0) + "%";
        pct.textContent = fmtSize(e.loaded) + " / " + fmtSize(e.total);
      } else {
        pct.textContent = fmtSize(e.loaded) + " uploaded";
      }
    };

    let retries = 0;
    const maxRetries = 2;

    xhr.onload = () => {
      if (xhr.status >= 200 && xhr.status < 300) {
        bar.style.width = "100%";
        subHead.textContent = "Done";
        pct.textContent = fmtSize(file.size) + " · uploaded";
        log('upload', 'complete name=' + file.name);
        loadFiles();
      } else if (xhr.status === 401) {
        logout();
      } else {
        subHead.textContent = "Failed";
        let reason = "Upload error (" + xhr.status + ")";
        try {
          const err = JSON.parse(xhr.responseText);
          if (err.error) reason = err.error;
        } catch (_) {}
        pct.textContent = reason;
        log('upload', 'failed name=' + file.name + ' reason=' + reason);
      }
    };

    xhr.onerror = () => {
      if (retries < maxRetries) {
        retries++;
        subHead.textContent = "Retrying (" + (retries + 1) + "/" + (maxRetries + 1) + ")…";
        log('upload', 'retry name=' + file.name + ' attempt=' + (retries + 1));
        setTimeout(() => xhr.send(fd), 1500 * (retries + 1));
      } else {
        subHead.textContent = "Failed";
        pct.textContent = "Connection lost";
        setConn(false);
        log('upload', 'failed name=' + file.name + ' reason=connection-lost');
      }
    };

    xhr.ontimeout = () => {
      subHead.textContent = "Timeout";
      pct.textContent = "Upload timed out — try again";
      log('upload', 'timeout name=' + file.name);
    };

    xhr.send(fd);
  }

  /* ---------- periodic heartbeat ---------- */
  setInterval(() => {
    if (state.token) loadFiles();
  }, 8000);

  /* ---------- boot ---------- */
  loadFilters();
  showPinModal();
})();
''';
  static const String appJsType = "application/javascript; charset=utf-8";

}
