#!/usr/bin/env python3
"""Regenerate lib/server/web_assets.dart from assets/web/*.

The foreground-service isolate can't use Flutter's rootBundle, so the browser
HTML/CSS/JS are embedded as Dart string constants. Run this after editing the
files under assets/web/.
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
WEB = ROOT / "assets" / "web"
OUT = ROOT / "lib" / "server" / "web_assets.dart"

ASSETS = [
    ("indexHtml", "index.html", "text/html; charset=utf-8"),
    ("stylesCss", "styles.css", "text/css; charset=utf-8"),
    ("appJs", "app.js", "application/javascript; charset=utf-8"),
]


def main() -> None:
    parts = [
        "// GENERATED by tool/gen_web_assets.py — mirrors assets/web/*.\n",
        "// Embedded as constants so the foreground-service isolate "
        "(no rootBundle) can serve them.\n",
        "// If you edit the web assets, regenerate this file.\n\n",
        "class WebAssets {\n",
    ]
    for var, fname, ctype in ASSETS:
        data = (WEB / fname).read_text(encoding="utf-8")
        if "'''" in data:
            raise SystemExit(f"{fname} contains a triple-single-quote; "
                             "it can't be embedded in a raw string.")
        parts.append(f'  static const String {var} = r\'\'\'{data}\'\'\';\n')
        parts.append(f'  static const String {var}Type = "{ctype}";\n\n')
    parts.append("}\n")
    OUT.write_text("".join(parts), encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
